name: learn-github-actions

on: push

jobs: 
   hellow-world-job:

     runs-on: ubuntu-latest

     steps:
        - name: check out repository code
          uses: action/checkout/@v4
        - run: "echo $(cat hello_world.txt)"
        
     
